ner:
 port: 9191
 host: "localhost"
bing:
 key: "AvOlbHckKDQPCdOpcCVFgOIIkU-s6ZqvDtBmH5TnpQ5lVXu9d4bwk-oYGfilG4Ca"
 max_connections: 5
output:
 filename: "data/output.js"
input:
 url: 'https://news.ycombinator.com/item?id=10152809'